---
- hosts: docker
  remote_user: remoto
  become_user: root
  become: true
  tasks:
    - name: crear directorio dockerComposeFTP si no existe
      file:
        path: /home/vagrant/dockerComposeFTP
        state: directory
        mode: '0755'
      become: yes
      become_user: root
    - name: copiar la carpeta docker-compose.yml a dockerComposeFTP 
      shell: cp -r /vagrant/ArchivoDC_FTP/docker-compose.yml /home/vagrant/dockerComposeFTP
      become: yes
      become_user: root
    - name: correr docker-compose
      args:
        chdir: /home/vagrant/dockerComposeFTP
      shell: docker-compose up -d
      become: yes
      become_user: root
    - name: verificamos que los contenedores docker-compose esten corriendo
      shell: docker ps >> /vagrant/ArchivoDC_FTP/ContenedoresCorriendo.txt
      become: yes
      become_user: root
    