---
- hosts: docker
  remote_user: remoto
  become_user: root
  become: true
  tasks:
    - name: crear directorio dockerComposeFlaskMySql si no existe
      file:
        path: /home/vagrant/dockerComposeFlaskMySql
        state: directory
        mode: '0755'
      become: yes
      become_user: root
    - name: copiar la carpeta app a dockerComposeFlaskMySql 
      shell: cp -r /vagrant/ArchivosDC_Flask_MySql/app /home/vagrant/dockerComposeFlaskMySql
      become: yes
      become_user: root
    - name: copiar la carpeta db a dockerComposeFlaskMySql 
      shell: cp -r /vagrant/ArchivosDC_Flask_MySql/db /home/vagrant/dockerComposeFlaskMySql
      become: yes
      become_user: root
    - name: copiar el archivo .gitlab-ci.yml a dockerComposeFlaskMySql 
      shell: cp /vagrant/ArchivosDC_Flask_MySql/.gitlab-ci.yml /home/vagrant/dockerComposeFlaskMySql
      become: yes
      become_user: root
    - name: copiar el archivo docker-compose.yml a dockerComposeFlaskMySql 
      shell: cp /vagrant/ArchivosDC_Flask_MySql/docker-compose.yml /home/vagrant/dockerComposeFlaskMySql
      become: yes
      become_user: root
    - name: correr docker-compose
      args:
        chdir: /home/vagrant/dockerComposeFlaskMySql
      shell: docker-compose up -d
      become: yes
      become_user: root
    - name: verificamos que los contenedores docker-compose esten corriendo
      shell: docker ps >> /vagrant/ArchivosDC_Flask_MySql/ContenedoresCorriendo.txt
      become: yes
      become_user: root
    